-- migration_v16.sql -- Reconciliacion LEGACY -> Supabase
-- 39 productos + 41 materiales (ON CONFLICT idempotente)
-- PAUSA 1: resumen aprobado por Ale antes de ejecutar

-- ═══════════════════════════════════════════════════════
-- MATERIALES (41 total, UPDATE si ya existe, INSERT si no)
-- ═══════════════════════════════════════════════════════
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('petg_gris', 'PETG Gris', 'PETG', 'Gris', 'MakerPanda', 25000.0, 19920.0, 2000, '2026-05-20', 19920.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('petg_naranja', 'PETG Naranja', 'PETG', 'Naranja', 'MakerPanda', 25000.0, 19920.0, 2000, '2026-05-20', 19920.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_seda_azul', 'PLA Silk Azul', 'SILK', 'Azul', 'MakerPanda', 30000.0, 23910.0, 1000, '2026-05-20', 23910.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_seda_gris', 'PLA Silk Gris', 'SILK', 'Gris', 'MakerPanda', 30000.0, 23910.0, 1000, '2026-05-20', 23910.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_rosa', 'PLA Rosa', 'PLA', 'Rosa', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-20', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_blanco', 'PLA Blanco', 'PLA', 'Blanco', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-20', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_negro', 'PLA Negro', 'PLA', 'Negro', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-20', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_celeste', 'PLA Celeste', 'PLA', 'Celeste', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_azul_marino', 'PLA Azul Marino', 'PLA', 'Azul Marino', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_azul_hielo', 'PLA Azul Hielo', 'PLA', 'Azul Hielo', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_rojo', 'PLA Rojo', 'PLA', 'Rojo', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_rojo_borgona', 'PLA Rojo Borgona', 'PLA', 'Rojo Borgona', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_verde', 'PLA Verde', 'PLA', 'Verde', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_verde_turquesa', 'PLA Verde Turquesa', 'PLA', 'Verde Turquesa', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_naranja', 'PLA Naranja', 'PLA', 'Naranja', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_amarillo', 'PLA Amarillo', 'PLA', 'Amarillo', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_amarillo_solar', 'PLA Amarillo Solar', 'PLA', 'Amarillo Solar', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_gris', 'PLA Gris', 'PLA', 'Gris', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_gris_pizarra', 'PLA Gris Pizarra', 'PLA', 'Gris Pizarra', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_violeta', 'PLA Violeta', 'PLA', 'Violeta', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_lavanda', 'PLA Lavanda', 'PLA', 'Lavanda', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_menta', 'PLA Menta', 'PLA', 'Menta', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_beige', 'PLA Beige', 'PLA', 'Beige', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_marron', 'PLA Marron', 'PLA', 'Marron', 'MakerPanda', 25000.0, 24140.0, 2000, '2026-05-28', 24140.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_madera', 'PLA Madera', 'PLA', 'Madera', 'MakerPanda', 25000.0, 23830.0, 2000, '2026-05-28', 23830.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_silk_dorado', 'PLA Silk Dorado', 'SILK', 'Dorado', 'MakerPanda', 30000.0, 23910.0, 1000, '2026-05-28', 23910.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_silk_cobre', 'PLA Silk Cobre', 'SILK', 'Cobre', 'MakerPanda', 30000.0, 23910.0, 1000, '2026-05-28', 23910.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_silk_negro_rojo', 'PLA Silk Negro/Rojo', 'SILK', 'Negro Rojo', 'MakerPanda', 30000.0, 23910.0, 1000, '2026-05-28', 23910.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_silk_negro_violeta', 'PLA Silk Negro/Violeta', 'SILK', 'Negro Violeta', 'MakerPanda', 30000.0, 23910.0, 1000, '2026-05-28', 23910.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_silk_azul_violeta', 'PLA Silk Azul/Violeta', 'SILK', 'Azul Violeta', 'MakerPanda', 30000.0, 23910.0, 1000, '2026-05-28', 23910.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('pla_silk_azul_verde', 'PLA Silk Azul/Verde', 'SILK', 'Azul Verde', 'MakerPanda', 30000.0, 23910.0, 1000, '2026-05-28', 23910.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('petg_negro', 'PETG Negro', 'PETG', 'Negro', 'MakerPanda', 25000.0, 19920.0, 2000, '2026-05-28', 19920.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('petg_blanco', 'PETG Blanco', 'PETG', 'Blanco', 'MakerPanda', 25000.0, 19920.0, 2000, '2026-05-28', 19920.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('petg_azul', 'PETG Azul', 'PETG', 'Azul', 'MakerPanda', 25000.0, 19920.0, 2000, '2026-05-28', 19920.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('petg_rojo', 'PETG Rojo', 'PETG', 'Rojo', 'MakerPanda', 25000.0, 19920.0, 2000, '2026-05-28', 19920.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('petg_verde', 'PETG Verde', 'PETG', 'Verde', 'MakerPanda', 25000.0, 19920.0, 2000, '2026-05-28', 19920.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('petg_amarillo', 'PETG Amarillo', 'PETG', 'Amarillo', 'MakerPanda', 25000.0, 19920.0, 2000, '2026-05-28', 19920.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('petg_plateado', 'PETG Plateado', 'PETG', 'Plateado', 'MakerPanda', 25000.0, 19920.0, 2000, '2026-05-28', 19920.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('petg_translucido', 'PETG Translucido', 'PETG', 'Translucido', 'MakerPanda', 25000.0, 19920.0, 2000, '2026-05-28', 19920.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('asa_negro', 'ASA Negro', 'ASA', 'Negro', 'MakerPanda', 30000.0, 34999.0, 1000, '2026-05-28', 34999.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;
INSERT INTO materials (material_id, name, tipo, color, proveedor, stock_gr, cost_kg, stock_minimo_gr, fecha_compra, precio_compra, activo) VALUES ('asa_blanco', 'ASA Blanco', 'ASA', 'Blanco', 'MakerPanda', 30000.0, 34999.0, 1000, '2026-05-28', 34999.0, 1) ON CONFLICT (material_id) DO UPDATE SET name=EXCLUDED.name, stock_gr=EXCLUDED.stock_gr, cost_kg=EXCLUDED.cost_kg, stock_minimo_gr=EXCLUDED.stock_minimo_gr, precio_compra=EXCLUDED.precio_compra, activo=EXCLUDED.activo;

-- ═══════════════════════════════════════════════════════
-- PRODUCTOS FALTANTES (39 nuevos, ON CONFLICT DO NOTHING)
-- ═══════════════════════════════════════════════════════
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('M19-FDE-S', 'admin', NULL, 'Fidget de escritorio — Botones', 'Botones táctiles de diferentes resistencias. Anclaje para el hiperfoco. Respaldo Aldana.', 'Fidgets', NULL, 8500.0, 45.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('M19-FDE-R', 'admin', NULL, 'Fidget de escritorio — Rueda', 'Rueda giratoria de precisión. Mecanismo silencioso para reuniones y trabajo profundo.', 'Fidgets', NULL, 9500.0, 52.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('M19-FDE-T', 'admin', NULL, 'Fidget de escritorio — Texturas', 'Placa de texturas multisensorial. Para regulación sensorial en escritorio.', 'Fidgets', NULL, 8000.0, 38.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('M19-FCO-U', 'admin', NULL, 'Fidget corporal — Reuniones', 'Para sostener en la mano durante presentaciones. Discreto, premium, efectivo.', 'Fidgets', NULL, 6500.0, 28.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('M19-KRS-U', 'admin', NULL, 'Kit Regulación Sensorial Niños', 'Set validado por Aldana para niños neurodivergentes. 3 piezas + guía de uso.', 'Kits', NULL, 22000.0, 0.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('M19-PNE-U', 'admin', NULL, 'Porta-notebook ejecutivo', 'Negro/oro. Acabado premium. Para laptop 13-15 pulgadas.', 'Oficina', NULL, 18000.0, 380.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('M19-BAN-U', 'admin', NULL, 'Bandeja de objetos personales', 'Ancla de escritorio. Diseño para llaves, reloj, airpods, tarjetas.', 'Oficina', NULL, 12000.0, 220.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('M19-ORD-U', 'admin', NULL, 'Organizador de escritorio modular', 'Sistema modular expandible. Negro con detalles oro.', 'Oficina', NULL, 15000.0, 290.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('M19-STB-U', 'admin', NULL, 'Stand de tablet — consultorio', 'Para consultorios de Aldana y escritorios ejecutivos. Ajustable.', 'Oficina', NULL, 14000.0, 260.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('VC-QPR-U', 'admin', NULL, 'Quiver Pro — soporte arco + 12 flechas', 'Soporte vertical arco + tubo 12 flechas + bandeja accesorios.', 'Vuelo Certero', NULL, 42000.0, 380.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('VC-FJG-U', 'admin', NULL, 'Fletcher Jig 360°', 'Jig de emplumado ajustable shafts 4-10mm. PETG + imanes.', 'Vuelo Certero', NULL, 15000.0, 120.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('VC-TBX-U', 'admin', NULL, 'Tournament Box — ajedrez', 'Caja magnética con tablero + compartimentos. Multicolor CFS.', 'Vuelo Certero', NULL, 55000.0, 0.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('VC-PPT-U', 'admin', NULL, 'Porta-pelotas tenis (3u)', 'Soporte de pared o escritorio para 3 pelotas de tenis.', 'Vuelo Certero', NULL, 10000.0, 90.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('VC-PRA-U', 'admin', NULL, 'Porta-raqueta de pared premium', 'Diseño premium. Sin el genérico de Amazon.', 'Vuelo Certero', NULL, 16000.0, 150.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('MEL-VSO-U', 'fer_produccion', NULL, 'Vinyl Sommelier — 27 divisores A-Z+#', 'Divisores con letras doradas fabricados en CFS. Para estante Ikea Kallax. El set completo.', 'Organización', NULL, 67000.0, 420.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('MEL-HWS-U', 'fer_produccion', NULL, 'Heavyweight Stabilizer', 'Peso de plato 320-350g cargado con monedas de peso real. Iniciales grabadas. Mejora la reproducción.', 'Audio técnico', NULL, 30000.0, 335.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('MEL-ISQ-U', 'fer_produccion', NULL, 'Iso-Spike Quartet — 4 spikes', 'Desacoplantes para parlantes. Base PETG + punta TPU. Reducción de vibración real y medible.', 'Audio técnico', NULL, 27000.0, 180.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('MEL-NPP-U', 'fer_produccion', NULL, 'Now Playing Premium', 'Expone el vinilo que está sonando. Base de corcho. Silueta tocadiscos o guitarra.', 'Display', NULL, 23000.0, 160.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('MEL-ADH-U', 'fer_produccion', NULL, 'Audiophile Desk Hub', 'Auriculares + porta-cartuchos + cables + bandeja stylus. Para el escritorio del melómano serio.', 'Escritorio', NULL, 42000.0, 480.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('MEL-SAU-U', 'fer_produccion', NULL, 'Stand armónica y ukelele', 'Para el músico con instrumentos pequeños en el espacio de escucha.', 'Instrumento', NULL, 15000.0, 140.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('MEL-PNB-U', 'fer_produccion', NULL, 'Porta-notebook Melómano', 'Negro/cobre. El escritorio del que trabaja escuchando vinilo.', 'Escritorio', NULL, 16000.0, 350.0, 0, 0, NULL, '2026-05-20', 1, 'propio_3d', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-MAC-S', 'oasis_del_estero', NULL, 'Maceta Orgánica Textura S', 'Textura topográfica en relieve · filamento stone/mármol · ideal suculentas y cactus', 'Macetas', '#2D6A4F', 4500.0, 435.0, 0, 0, 'OE-macetas-blancas-bandeja-negra-frente.jpg', '2026-05-20', 1, 'linea_propio', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-MAC-M', 'oasis_del_estero', NULL, 'Maceta Orgánica Textura M', 'Textura topográfica en relieve · filamento stone/mármol · plantas medianas', 'Macetas', '#2D6A4F', 7500.0, 726.0, 0, 0, 'OE-macetas-blancas-bandeja-negra-lateral.jpg', '2026-05-20', 1, 'linea_propio', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-MAC-BC-M', 'oasis_del_estero', NULL, 'Maceta Bicolor Diagonal M', 'CFS bicolor gris/negro · franjas diagonales · diseño exclusivo K2 Plus', 'Macetas', '#2D6A4F', 9500.0, 919.0, 0, 0, 'OE-maceta-bicolor-bandeja-blanca.jpg', '2026-05-20', 1, 'linea_propio', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-SEL-S', 'oasis_del_estero', NULL, 'Soporte Elevador para Maceta S', 'Base con 3 patas bola · eleva maceta 8cm · evita charcos · interior/exterior', 'Macetas', '#2D6A4F', 3200.0, 310.0, 0, 0, NULL, '2026-05-20', 1, 'linea_propio', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-SEL-M', 'oasis_del_estero', NULL, 'Soporte Elevador para Maceta M', 'Base con 3 patas bola · versión negra · combina con maceta bicolor', 'Macetas', '#2D6A4F', 4800.0, 465.0, 0, 0, 'OE-maceta-bicolor-soporte-negro-frente.jpg', '2026-05-20', 1, 'linea_propio', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-MRP-3', 'oasis_del_estero', NULL, 'Set 3 Marcadores de Plantas', 'Etiquetas identificadoras · palito + cartel · personalizables con nombre de planta', 'Jardinería', '#2D6A4F', 1800.0, 50.0, 0, 0, NULL, '2026-05-20', 1, 'linea_propio', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-MRP-5', 'oasis_del_estero', NULL, 'Set 5 Marcadores Personalizados', 'Con nombre de planta grabado + fecha de siembra · ideal regalo jardinero', 'Jardinería', '#2D6A4F', 2800.0, 80.0, 0, 0, NULL, '2026-05-20', 1, 'linea_propio', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-MRP-10', 'oasis_del_estero', NULL, 'Set 10 Marcadores Personalizados', 'Pack completo para colección de plantas · nombre + cuidados · por pedido', 'Jardinería', '#2D6A4F', 4500.0, 140.0, 0, 0, NULL, '2026-05-20', 1, 'linea_propio', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-TUT-S', 'oasis_del_estero', NULL, 'Tutor Espiral S (plantas 20–40cm)', 'Soporte helicoidal · PETG resistente · plantas trepadoras y aromáticas pequeñas', 'Jardinería', '#2D6A4F', 800.0, 30.0, 0, 0, NULL, '2026-05-20', 1, 'linea_propio', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-TUT-M', 'oasis_del_estero', NULL, 'Tutor Espiral M (plantas 40–70cm)', 'Soporte helicoidal · PETG resistente · tomates cherry, albahaca, trepadoras medianas', 'Jardinería', '#2D6A4F', 1200.0, 50.0, 0, 0, NULL, '2026-05-20', 1, 'linea_propio', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-TUT-3PK', 'oasis_del_estero', NULL, 'Pack 3 Tutores Espiral (surtido S+M+L)', 'Pack mixto ideal para jardín en balcón · 3 tamaños · color a elección', 'Jardinería', '#2D6A4F', 3200.0, 150.0, 0, 0, NULL, '2026-05-20', 1, 'linea_propio', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-CAR-U', 'oasis_del_estero', NULL, 'Cartelito Identificador de Maceta', 'Plaquita con nombre del propietario + especie · personalizable · por unidad', 'Jardinería', '#2D6A4F', 600.0, 15.0, 0, 0, NULL, '2026-05-20', 1, 'linea_propio', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-SEM-U', 'oasis_del_estero', NULL, 'Organizador de Semillas (6 compartimentos)', 'Caja modular 6 divisiones con tapa y etiqueta · para almacenar semillas', 'Jardinería', '#2D6A4F', 3500.0, 115.0, 0, 0, NULL, '2026-05-20', 1, 'linea_propio', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-KIT-JAR', 'oasis_del_estero', NULL, 'Kit Jardinero Urbano', 'Maceta Orgánica S + Set 5 Marcadores + Tutor M · caja kraft · regalo completo', 'Kits', '#2D6A4F', 12000.0, 0.0, 0, 0, 'OE-macetas-bandeja-conjunto.jpg', '2026-05-20', 1, 'kit_mixto', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('ODE-KIT-SUC', 'oasis_del_estero', NULL, 'Kit Suculentas', '2x Maceta Orgánica S + Bandeja Oval S + Set 3 Marcadores · listo para regalar', 'Kits', '#2D6A4F', 18000.0, 0.0, 0, 0, 'OE-macetas-bandeja-conjunto.jpg', '2026-05-20', 1, 'kit_mixto', 'publico', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('FSP-001', 'francisco_sport', NULL, 'Cajita Porta-Figuritas AFA', 'Boveda conmemorativa tricampeona con el escudo oficial AFA y tres estrellas en relieve dorado. Disponible en negro, blanco y celeste. Bisagra y cierre a presion. Edicion 1978 1986 2022.', 'Coleccionables', '#F97316', 10000.0, 1470.0, 0, 0, 'static/productos/sport/cajita_afa_blanco.jpg', '2026-05-20', 1, 'propio_3d', 'interno', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('FSP-002', 'francisco_sport', NULL, 'Cajita Porta-Figuritas FIFA 26', 'Boveda conmemorativa FIFA 2026 con la Copa del Mundo en relieve dorado sobre panel contrastante. Disponible en negro, blanco y celeste. Bisagra y cierre resistente. Edicion limitada.', 'Coleccionables', '#F97316', 10000.0, 1470.0, 0, 0, 'static/productos/sport/cajita_fifa_negro.jpg', '2026-05-20', 1, 'propio_3d', 'interno', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (sku, client_id, material_id, name, description, categoria, color, price, weight_gr, tiempo_impresion_min, stock, imagen_url, fecha_alta, activo, tipo_producto, visibilidad, proveedor_ref, precio_reventa, precio_socio) VALUES ('FSP-003', 'francisco_sport', NULL, 'Cajita Porta-Figuritas Argentina FIFA', 'Boveda con las franjas albicelestes y la Copa FIFA en relieve dorado. Efecto holograma con los colores de la Seleccion. Bisagra y cierre a presion. El regalo ideal para el hincha tricampeon.', 'Coleccionables', '#F97316', 10000.0, 1470.0, 0, 0, 'static/productos/sport/cajita_arg_holograma.jpg', '2026-05-20', 1, 'propio_3d', 'interno', NULL, 0.0, 0.0) ON CONFLICT (sku) DO NOTHING;